export const APIRoutes = {
  loginAPI: "/sign/login",
  LandingReports: "/Home/LandingReport",
  Allteacher: "/Home/GetTeachers",
  //users
  getProfile: "/SharePanel/GetProfileInfo",
  AllUsers: "/User/UserMannage",
  UserDetails: "/User/UserDetails",
  CreateUser: "/User/CreateUser",
  UpdateUser: "/User/UpdateUser",
  DeleteUser: "/User/DeleteUser",
  UserMannage: "/User/UserMannage",
  //courses
  getCourseTop: "/Home/GetCoursesTop",
  getCourseList: "/Course/CourseList",
  GetCreateCourse: "/Course/GetCreate",
  CreateCourse: "/Course",
  CourseDetails: "/Course",
  CourseEdit: "/Course",
  CourseTech: "/Course/AddCourseTechnology",
  ChangeCourseActive: "/Course/ActiveAndDeactiveCourse",
  CourseReserve: "/CourseReserve",
  AddCourseGroup: "/CourseGroup",
  GetCourseGroup: "/CourseGroup/GetCourseGroup",
  acceptCourseReserveAPI: "/CourseReserve/SendReserveToCourse",
  //news
  GetListNewsCategory: "/News/GetListNewsCategory",
  getArticleList: "/News/AdminNewsFilterList",
  CreateNews: "/News/CreateNews",
  ArticleDetails: "/News/",
  UpdateNewsCategory: "/News/UpdateNewsCategory",
  CreateNewsCategory:"/News/CreateNewsCategory",
  //comments
  getCommentsList: "/Course/CommentManagment",
  AcceptCourseComment: "/Course/AcceptCourseComment",
  RejectCourseComment: "/Course/RejectCourseComment",
  DeleteCourseComment: "/Course/DeleteCourseComment",
  userComments: "/Course/CommentManagment",
  GetCourseCommnets: "/Course/GetCourseCommnets",
  AddReplyCourseComment: "/Course/AddReplyCourseComment",
};
